name: CI
on: [ push, pull_request ]
jobs:
  Build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/wrapper-validation-action@v1
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Cache/Uncache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build
      - name: Reference
        run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
        id: ref
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tnttime-${{ steps.ref.outputs.branch }}
          path: build/libs
