name: Recent release
on:
  release:
    types:
      - published
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Wrapper an executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload to GitHub
        uses: AButler/upload-release-assets@v2.0.2
        with:
          files: 'build/libs/*.jar;LICENSE'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
